### ISSUE TITLE
Interrupt examples.

### ISSUE THREAD

**Issue by Marcato0o** [ivmarkov/rust-esp32-std-demo#120]
Add some timer-based interrupt example would be useful, since I can't find it anywhere.

**Comment by ivmarkov** [comment]
Quite a few in the meantime, both sync and async, here: https://github.com/esp-rs/esp-idf-hal/tree/master/examples

I don't plan to extend `rust-esp32-std-demo` with examples anymore. Rather, split it and merge its examples into `esp-idf-hal` and `esp-idf-svc`.
