### ISSUE TITLE
Time synchronisation example

### ISSUE THREAD

**Issue by mohs8421** [ivmarkov/rust-esp32-std-demo#121]
I would like to sync the system clock and get unixtimestamps, but I am unsure how to do it.

I already found out, that I have to start with this:
```rust
use esp_idf_svc::sntp::EspSntp;

let sntp = EspSntp::new_default().unwrap();
```

but how do I access the correct time now?

**Comment by mohs8421** [comment]
After some searching, I found a solution, which looks like this:
```rust
pub fn time() -> i64 {
    let mut timer: time_t = 0;
    unsafe {
        esp_idf_sys::time(&mut timer);
    }
    timer as i64
}
```
This might be a nice small addition to the examples.

**Comment by ivmarkov** [comment]
`SysTime` from `esp-idf-svc`.
