### ISSUE TITLE
Serving HTTP in Access Point Mode

### ISSUE THREAD

**Issue by 3d-t** [ivmarkov/rust-esp32-std-demo#135]
I have a use case where you don't want a build-in SSID and PASS for connecting to a wifi network. Instead the user should connect to the ESP accesspoint and then a web page shows where the user can enter the SSID and PASS of the local network. When provided the info is stored in EEPROM for future use and a connection to the wifi network is created.I have an implementation in .cpp (platform.io) where this works by connecting to 192.168.1.4 by default. This IP address can be changed.

When running the demo I can connect to the accesspoint "aptest' but what IP address should I use to connect to the 'httpd' function in the demo?

**Comment by ivmarkov** [comment]
The [default one](https://github.com/esp-rs/embedded-svc/blob/master/src/ipv4.rs#L185).
