### ISSUE TITLE
Updating to current versions ( questions )

### ISSUE THREAD

**Issue by bbrietzke** [ivmarkov/rust-esp32-std-demo#145]
I love the example and have found it very useful.  There have been a number of things that i have discovered and figured out thanks to this code.

It is also out of date with regards to a number of features ( i.e. web server ).  I was wondering if I could help with the code changes that i've discovered and if that would be useful.

I can't help with the hardware tests/configurations, don't have the equipment, resources or headspace for that right now.

**Comment by ivmarkov** [comment]
Feel free to open PRs for stuff that you would like to see improved.

**Comment by ivmarkov** [comment]
Closing. Please follow with PRs for stuff you would like to see improved.
