### ISSUE TITLE
Add Wi-Fi callback example

### ISSUE THREAD

**Issue by owenthewizard** [ivmarkov/rust-esp32-std-demo#161]
I'm trying to use [WifiDriver::set_callbacks](https://docs.esp-rs.org/esp-idf-svc/esp_idf_svc/wifi/struct.WifiDriver.html#method.set_callbacks) but I'm not successful. I think an example would be helpful.

**Comment by owenthewizard** [comment]
I'm trying to implement this in idiomatic Rust: https://github.com/dokmic/eth2wlan/blob/master/main/main.c

**Comment by ivmarkov** [comment]
Did you check the README? Feel free to open this issue at [esp-idf-svc](https://github.com/esp-rs/esp-idf-svc) instead.

With that said, I can't write an example for every use case, as this is supported on my free time. The `esp-idf-*` crates are a community-driven effort, so ideally, folks achieving something open PRs (including for examples) and thus help in driving the crates forwards.

Even describing your issue in more details could be helpful.
