### ISSUE TITLE
esp32s3_usb_otg_hello_world crash - double call of Peripherals::take

### ISSUE THREAD

**Issue by georgik** [ivmarkov/rust-esp32-std-demo#28]
Build command:
```
cargo +esp-1.56.0.1 espflash --target xtensa-esp32s3-espidf --release --features "esp32s3_usb_otg" --monitor COM5
```

Crash on line:
https://github.com/ivmarkov/rust-esp32-std-demo/blob/main/src/main.rs#L660

Reason: `Peripherals::take().unwrap()` - invoked twice:
- https://github.com/ivmarkov/rust-esp32-std-demo/blob/main/src/main.rs#L113
- https://github.com/ivmarkov/rust-esp32-std-demo/blob/main/src/main.rs#L660

Workaround: remove one call of Peripherals

Note: espflash was installed by command: `cargo install cargo-espflash --git https://github.com/jessebraham/espflash.git --branch fixes/target-arg`
Note 2: resulting app is slightly bigger then default partition, after deleting some code, the app fits. We're investigating options to set partition size via espflash.

**Comment by ivmarkov** [comment]
Fixed in https://github.com/ivmarkov/rust-esp32-std-demo/commit/876a42e9a70843e88ec2fc4deb8f1582ed8c091a
