### ISSUE TITLE
rust-analyzer not consider "arch = xtensa"

### ISSUE THREAD

**Issue by hongquan** [ivmarkov/rust-esp32-std-demo#31]
I'm opening this repo in VS Code. Already installed ESP-IDF, already selected `xtensa-esp32-espidf`, already have _rust-toolchain.toml_ file with:

```toml
[toolchain]
channel = "esp"
```

But I got this block of code inactive:

![image](https://user-images.githubusercontent.com/314607/140519785-50ea31ee-38df-4c96-bf7a-fd05dc892c0a.png)

Is it Ok, or what should I do to let rust-analyzer highlight it.

**Comment by ivmarkov** [comment]
It is not OK and it is a (minor) bug. I've pushed a fix. Please re-pull and the problem should be fixed. Just have in mind that rust backtraces are in a very shaky state. They are not stabilized in rust itself, and on the esp-idf they only work with the esp-idf v4.3 (no later).
