### ISSUE TITLE
ESP 8266 support.

### ISSUE THREAD

**Issue by ganeshrvel** [ivmarkov/rust-esp32-std-demo#43]
First of all thank you for the wonderful work in making rust accessible for the IOT devs. I was just curious whether it would be possible to make this code work on an ESP 8266 chip. 

Any plans to support 8266?

Cheers!

**Comment by ivmarkov** [comment]
Not really. I personally will put support for ESP 8266 in embuild / esp-idf-sys only if/when ESP8266 becomes a supported platform by the `ESP-IDF` SDK itself. (It currently has a separate SDK which is not really compatible with ESP-IDF.)

Other people expressed interest in the [Matrix channel](https://app.element.io/#/room/#esp-rs:matrix.org) recently in building support for ESP 8266 even with its current non-standard SDK. If you are interested, perhaps you should talk to them.
