### ISSUE TITLE
Suggest 'rustup override set' rather than 'rustup default'

### ISSUE THREAD

**Issue by p2mate** [ivmarkov/rust-esp32-std-demo#58]
'rustup default' will change the default toolchain for all rust builds done by the same user. This may cause an older rustc version to be used for non-esp32 builds and also may cause those builds to fail if they require a newer version than the Espressif provided one. Hence it's better to limit the toolchain override to the esp32 project by using rustup override set esp in the root of the project.

**Comment by ivmarkov** [comment]
I've added a small comment as per your suggestion, but I'm unwilling to remove all references to `rustup default`. Often we have newcomers to Rust trying out the crate, and having as simple as possible steps for them is actually better. Even at the expense that the esp toolchain might be used for other stuff as well. 

By the way, another option would've been  to put a `rust-toolchain.toml` file as [the esp-idf-template](https://github.com/esp-rs/esp-idf-template/blob/master/cargo/rust-toolchain.toml) crate does, but I think we are getting too far into the weeds with these things.
