### ISSUE TITLE
clippy errors

### ISSUE THREAD

**Issue by brianmay** [ivmarkov/rust-esp32-std-demo#65]
Just curious what is wrong with clippy in the CI?

e.g. https://github.com/ivmarkov/rust-esp32-std-demo/runs/5257226106?check_suite_focus=true

It seems to be complaining about errors in embedded-svc.

But my understanding is that as we use the `--no-deps` option we shouldn't be checking for errors in dependencies.

Also if I run the same command locally it works.

**Comment by ivmarkov** [comment]
Issues with latest Rust nightly and GATs.

**Comment by ivmarkov** [comment]
Looking at it since an hour or so, but not sure what is going on. Might be a regression in the compiler itself, as the error looks bogus.

**Comment by ivmarkov** [comment]
Apparently they fixed something because since this morning, we get clean CIs again.

Perhaps [this one](https://github.com/rust-lang/rust/pull/94088).
