### ISSUE TITLE
Accessing web server when running in QEMU

### ISSUE THREAD

**Issue by callmephilip** [ivmarkov/rust-esp32-std-demo#71]
I was able to get the app to run in QEMU using provided instructions. Is there a way to access HTTP server inside a browser on the host machine?

**Comment by ivmarkov** [comment]
I guess it is possible, but you have to consult the [qemu documentation](https://qemu.readthedocs.io/en/latest/system/devices/net.html) as there is nothing Rust or ESP-IDF specific in it.
