### ISSUE TITLE
Async TcpStream

### ISSUE THREAD

**Issue by 1291431532** [ivmarkov/rust-esp32-std-demo#75]
I encountered an exception while running the following code
```rust
let stream = smol::Async::<std::net::TcpStream>::connect("one.one.one.one:80".to_socket_addrs().unwrap().next().unwrap()).await;
```
Err(Os { code: 88, kind: Unsupported, message: "Function not implemented" })

The error is here 
https://github.com/esp-rs-compat/socket2/blob/9cdd55ac7abc59aa6613a1302eb3d8bcdbe56ab7/src/socket.rs#L707

**Comment by ivmarkov** [comment]
This should be fixed now. You might need to remove your `socket2` checkout from `~/.cargo` as the fix was force-pushed.

Please reopen if it still does not work for you.
