### ISSUE TITLE
Use cargo espflash instead of esptool for qemu image generation

### ISSUE THREAD

**Issue by svenstaro** [ivmarkov/rust-esp32-std-demo#82]
Currently `qemu.sh` depends on `esptool.py` and that means we also have to carry the manually pre-generated stuff in `qemu-bins/`. This is somewhat inelegant and I've had good success using `cargo espflash` instead. I'd like to propose a PR for this after my current work is merged which is required for this to work: https://github.com/esp-rs/espflash/pull/160 and https://github.com/esp-rs/espflash/pull/162. What do you think?

**Comment by ivmarkov** [comment]
Moving to espflash is of course very welcome!
