### ISSUE TITLE
Forum to ask questions regarding rust on esp32

### ISSUE THREAD

**Issue by enelson1001** [ivmarkov/rust-esp32-std-demo#95]
Is there a forum where one can ask questions on how to implement features or future features of rust esp32 ?
I have questions using periodic timer.
This doesn't seem the correct place to ask such questions
Thanks

**Comment by ivmarkov** [comment]
Here: https://matrix.to/#/#esp-rs:matrix.org

I've added a link to the readme as well.

**Comment by enelson1001** [comment]
This is what I see when I click on the link.

![Screenshot of link](https://user-images.githubusercontent.com/43481343/173626399-5dc698c1-53d3-4e4b-b22d-14ebc61adf92.png)

**Where is discussion forum for esp32-rust???

**Comment by enelson1001** [comment]
Never mind figured it out
